Naveen hw1
NataRazmochaeva/pc-2021-6300 pull request #1
Opened 2021-03-05 16:37 UTC by naveenpardeep

please check mam.

Thank You
Yours Sincerely 
Naveen

2021-03-06 14:13 UTC, MOUBAREK1998 commented
thank you

2021-03-10 08:55 UTC, NataRazmochaeva requested changes
Some remarks to task 2

2021-03-10 08:55 UTC, NataRazmochaeva commented on Naveen-hw1/task1.c
> +}
Task 1 is accepted

2021-03-10 08:55 UTC, NataRazmochaeva commented on Naveen-hw1/task2.c
> +
Please add outputting of ppid

2021-03-10 08:55 UTC, NataRazmochaeva commented on Naveen-hw1/task2.c
> +
Please add outputting of ppid

2021-03-10 08:55 UTC, NataRazmochaeva commented on Naveen-hw1/task2.c
> +                printf("N3 parent of N4 and pid is  %d\n",getppid());
Please add outputting of ppid

2021-03-13 03:57 UTC, merged